# Generated by Django 5.1.6 on 2025-02-18 11:46

from django.db import migrations


def defining_a_new_building(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")

    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)

    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)

    Flat.objects.filter(construction_year__isnull=True).update(new_building=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building_alter_flat_has_balcony'),
    ]

    operations = [
        migrations.RunPython(defining_a_new_building),
    ]

