# Generated by Django 3.2.24 on 2025-02-12 14:13

from django.db import migrations


def defining_a_new_building(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all():
        if flat.construction_year is not None:
            flat.new_building = flat.construction_year >= 2015
        else:
            flat.new_building = None 
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(defining_a_new_building),
    ]