# Generated by Django 3.2.24 on 2025-02-12 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='likes',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='liked_users', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
