# Generated by Django 5.1.6 on 2025-02-18 12:14

from django.db import migrations, models
from django.db.models import F
import phonenumbers


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")

    flats = Flat.objects.exclude(owners_phonenumber__isnull=True).iterator()

    updates = []
    for flat in flats:
        try:
            parsed_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
            if phonenumbers.is_valid_number(parsed_number):
                flat.normalized_number = phonenumbers.format_number(
                    parsed_number, phonenumbers.PhoneNumberFormat.E164
                )
            else:
                flat.normalized_number = None
        except phonenumbers.NumberParseException:
            flat.normalized_number = None
        
        updates.append(flat)

    Flat.objects.bulk_update(updates, ["normalized_number"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_normalized_number'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers),
    ]
