# Generated by Django 3.2.24 on 2025-02-12 14:31

from django.db import migrations
import phonenumbers


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all():
        if flat.owners_phonenumber:
            try:
                parsed_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
                if phonenumbers.is_valid_number(parsed_number):
                    flat.owner_pure_phone = phonenumbers.format_number(
                        parsed_number, phonenumbers.PhoneNumberFormat.E164
                    )
                else:
                    flat.owner_pure_phone = None
                flat.save(update_fields=["owner_pure_phone"])
            except phonenumbers.NumberParseException:
                flat.owner_pure_phone = None
                flat.save(update_fields=["owner_pure_phone"])


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0008_alter_flat_has_balcony"),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers),
    ]