# Generated by Django 5.1.6 on 2025-02-18 13:28

from django.db import migrations


def moving_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    owner_dict = {}

    for flat in Flat.objects.all().iterator():

        if flat.owner not in owner_dict:
            owner_dict[flat.owner] = Owner.objects.create(
                owner_name=flat.owner,
                owners_phonenumber=flat.owners_phonenumber,
                owner_pure_phone=flat.normalize_phone
            )
        owner_dict[flat.owner].flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
    ]
