# Generated by Django 5.1.6 on 2025-02-18 13:28

from django.db import migrations, transaction


def moving_owners(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")

    with transaction.atomic():
        for owner in Owner.objects.all().iterator():
            flats = Flat.objects.filter(owners=owner)  
            for flat in flats:
                owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0010_owner"),
    ]

    operations = [
        migrations.RunPython(moving_owners),
    ]
