# Generated by Django 3.2.24 on 2025-02-12 14:48

from django.db import migrations
from phonenumbers import parse, is_valid_number, format_number, PhoneNumberFormat


def normalize_phone_numbers(phone_number):
    if not phone_number:
        return None
    parsed_number = parse(phone_number, 'RU')
    return format_number(parsed_number, PhoneNumberFormat.INTERNATIONAL) if is_valid_number(parsed_number) else None


def moving_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    owner_dict = {}

    for flat in Flat.objects.all().iterator():

        if flat.owner not in owner_dict:
            owner_dict[flat.owner] = Owner.objects.create(
                owner_name=flat.owner,
                owners_phonenumber=flat.owners_phonenumber,
                owner_pure_phone=normalize_phone_numbers(flat.owners_phonenumber)
            )
        owner_dict[flat.owner].flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(moving_owners),
    ]
