# Generated by Django 3.2.24 on 2025-02-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20250212_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_test',
            new_name='complaint_text',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='normalized_number',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
    ]
