# Generated by Django 3.2.24 on 2025-02-13 18:12

from django.db import migrations


def defining_a_new_building(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")

    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)

    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)

    Flat.objects.filter(construction_year__isnull=True).update(new_building=None)


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_flat_new_building"),
    ]

    operations = [
        migrations.RunPython(defining_a_new_building),
    ]

