# Generated by Django 3.2.24 on 2025-02-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20250213_2059'),
        ('property', '0015_auto_20250213_2112'),
    ]

    operations = [
    ]
