# Generated by Django 3.2.24 on 2025-02-13 18:18

from django.db import migrations
import phonenumbers


def normalize_phone_numbers(apps, schema_editor):
    Owner = apps.get_model("property", "Owner")

    for owner in Owner.objects.iterator():
        if owner.phonenumber:
            try:
                parsed_number = phonenumbers.parse(owner.phonenumber, "RU")
                if phonenumbers.is_valid_number(parsed_number):
                    owner.normalized_number = phonenumbers.format_number(
                        parsed_number, phonenumbers.PhoneNumberFormat.E164
                    )
                else:
                    owner.normalized_number = None
            except phonenumbers.NumberParseException:
                owner.normalized_number = None

            owner.save(update_fields=["normalized_number"])


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0008_alter_flat_has_balcony"),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers),
    ]
