# Generated by Django 3.2.24 on 2025-02-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_merge_0014_auto_20250213_2059_0015_auto_20250213_2112'),
        ('property', '0017_auto_20250213_2118'),
    ]

    operations = [
    ]
