# Generated by Django 3.2.24 on 2025-02-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_merge_20250213_2119'),
        ('property', '0019_auto_20250213_2126'),
    ]

    operations = [
    ]
