# Generated by Django 3.2.24 on 2025-02-13 18:33

from django.db import migrations, transaction


def moving_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.iterator():
        try:
            with transaction.atomic():
                new_owner, created = Owner.objects.get_or_create(
                    name=owner.name,
                    phonenumber=owner.phonenumber,
                    normalized_number=owner.normalized_number
                )

                flats = owner.flats.all()
                new_owner.flats.set(flats)

        except Exception as e:
            print(f"Ошибка для {owner.name}: {e}")


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0010_owner"),
    ]

    operations = [
        migrations.RunPython(moving_owners),
    ]
