# Generated by Django 3.2.24 on 2025-02-13 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_merge_20250213_2130'),
        ('property', '0021_auto_20250213_2133'),
    ]

    operations = [
    ]
