# Generated by Django 3.2.24 on 2025-02-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_alter_flat_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_text',
            new_name='message',
        ),
    ]
